USE DATABASE DATA_SHARING;
USE SCHEMA shared;
DROP VIEW IF EXISTS VW_CAMPAIGN_DATA;
CREATE SECURE VIEW VW_CAMPAIGN_DATA AS 
   SELECT CD.* 
   FROM FACTS.CAMPAIGN_DATA CD
   INNER JOIN FACTS.CRM_DATA CRM ON CRM.OrderID = CD.OrderID;
GRANT SELECT ON VIEW vw_campaign_data TO SHARE provider_campaign_data; 


