USE DATABASE DATA_SHARING_CL;
USE SCHEMA shared;
DROP VIEW IF EXISTS VW_CAMPAIGN_DATA;
CREATE SECURE VIEW VW_CAMPAIGN_DATA AS 
   SELECT CL.* 
   FROM CARDLYTICS.CAMPAIGN_DATA CL
   INNER JOIN CARDLYTICS.CRM_DATA AIR ON AIR.OrderID = CL.OrderID;
GRANT SELECT ON VIEW vw_campaign_data TO SHARE cardlytics_campaign_data; 


