USE DATABASE DATA_SHARING_CL;
DROP SCHEMA IF EXISTS CARDLYTICS;
CREATE SCHEMA CARDLYTICS COMMENT = 'Cardlytics test schema';
DROP SCHEMA IF EXISTS SHARED;
CREATE SCHEMA SHARED COMMENT = 'data shared by Cardlytics';
