DROP VIEW IF EXISTS SHARED.VW_CAMPAIGN_DATA;
CREATE SECURE VIEW SHARED.VW_CAMPAIGN_DATA AS 
   SELECT CL.* 
   FROM CARDLYTICS.CAMPAIGN_DATA CL
   INNER JOIN CARDLYTICS.CRM_DATA AIR ON AIR.OrderID = CL.OrderID;

