USE DATABASE DATA_SHARING_AIR;
DROP SCHEMA IF EXISTS AIRBNB;
CREATE SCHEMA AIRBNB COMMENT = 'Airbnb test schema';
DROP SCHEMA IF EXISTS SHARED;
CREATE SCHEMA SHARED COMMENT = 'data shared by AIRBNB';
